### fetching the dataframe

In [1]:
from sklearn.datasets import load_boston
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

boston_dataset = load_boston()

### creating data frame

In [2]:
boston_df = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)
boston_df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [3]:
boston_df['MEDV'] = boston_dataset.target
boston_df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [4]:
boston_df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [5]:
boston_df.shape

(506, 14)

In [6]:
X = boston_df.iloc[:,1:-1].values
y = boston_df.iloc[:,-1].values

In [7]:
from sklearn import model_selection
Xtrain,Xtest,ytrain,ytest = model_selection.train_test_split(X,y, test_size =0.3, random_state =25)

### applying linear Regression

In [8]:
from sklearn.linear_model import LinearRegression

lm = LinearRegression()
lm.fit(Xtrain, ytrain)

ypred = lm.predict(Xtest)

In [9]:
print(lm.intercept_)
print(lm.coef_)

37.3718195321095
[ 4.70283409e-02  3.86375721e-02  8.30546707e-01 -1.82698177e+01
  4.03216279e+00 -4.49896677e-03 -1.47732114e+00  3.09047845e-01
 -1.67973508e-02 -9.81879609e-01  8.72574573e-03 -4.91310730e-01]

In [10]:
from math import sqrt
from sklearn.metrics import r2_score, mean_squared_error

print(sqrt(mean_squared_error(ytest,ypred)))

4.678096212502479

### Ridge Regression

In [13]:
from sklearn.linear_model import Ridge
ridgereg = Ridge(alpha =0.001, normalize = True)
ridgereg.fit(Xtrain , ytrain)

ytrain_ridge = ridgereg.predict(Xtrain)
ytest_ridge =ridgereg.predict(Xtest)

print(sqrt(mean_squared_error(ytrain,ytrain_ridge)))
print(sqrt(mean_squared_error(ytest,ytest_ridge)))

print('R2 value/ Coefficient of determination: {}'.format(ridgereg.score(Xtest,ytest)))

4.817222596043212
4.675536113621845
R2 value/ Coefficient of determination: 0.7098630721950647

### Lasso Regression

In [14]:
from sklearn.linear_model import Lasso
lassoreg = Lasso(alpha =0.001, normalize = True)
lassoreg.fit(Xtrain , ytrain)

ytrain_lasso = lassoreg.predict(Xtrain)
ytest_lasso =lassoreg.predict(Xtest)

print(sqrt(mean_squared_error(ytrain,ytrain_lasso)))
print(sqrt(mean_squared_error(ytest,ytest_lasso)))

print('R2 value/ Coefficient of determination: {}'.format(lassoreg.score(Xtest,ytest)))

4.819665225925888
4.665992447008002
R2 value/ Coefficient of determination: 0.7110463136648693

### Elasticnet Regression

In [16]:
from sklearn.linear_model import ElasticNet
elasticreg = ElasticNet(alpha =0.001, normalize = True)
elasticreg.fit(Xtrain , ytrain)

ytrain_elastic = elasticreg.predict(Xtrain)
ytest_elastic =elasticreg.predict(Xtest)

print(sqrt(mean_squared_error(ytrain,ytrain_elastic)))
print(sqrt(mean_squared_error(ytest,ytest_elastic)))

print('R2 value/ Coefficient of determination: {}'.format(elasticreg.score(Xtest,ytest)))

4.990117085447628
4.769187659498942
R2 value/ Coefficient of determination: 0.6981237130915618